config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                  'static_pages#home'
  get     'signup'   =>  'users#new'
  get     'login'    =>  'sessions#new'
  post    'login'    =>  'sessions#create'
  delete  'logout'   =>  'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<%= link_to "Red Social", '#', id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
	          <li><%= link_to "Usuarios", users_path %></li>
	          <li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	              <%= @current_user.name%> <b class="caret"></b>
	            </a>
	            <ul class="dropdown-menu">
	              <li><%= link_to "Perfil", current_user %></li>
	              <li><%= link_to "Config", edit_user_path(current_user) %></li>
	              <li class="divider"></li>
	              <li>
	                <%= link_to "Cerrar session", logout_path, method: "delete" %>
	              </li>
	            </ul>
	          </li>
	        <% else %>
	          <li><%= link_to "Iniciar sesion", login_path %></li>
	        <% end %>
		</ul>
			</nav>
		</div>
	</header><!-- /header -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>